### PR TITLE
feat(rest): toString objects without keys before buildQueryString

### PR DESCRIPTION
**Pull request by doktordirk**
this allows eg Date to be used in criteria

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/157)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
You're already able to use dates in critera.

**Comment by doktordirk** [comment]
dates yes, but not Date (as in instanceof Date)

**Comment by RWOverdijk** [comment]
Are you sure? Because it works for me (with sails) in ORM.

**Comment by doktordirk** [comment]
not sure

**Pull request closed without merging**
