### PR TITLE
feat(project); improve typings

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Is this es6?

Also, last commit has a semicolon in stead of a colon.

**Comment by doktordirk** [comment]
no, yes. gets removed in building. it's just the same aurelia repos do

**Comment by doktordirk** [comment]
really should do that.

needs update

**Comment by doktordirk** [comment]
needs different d.ts build. thus continued there https://github.com/SpoonX/aurelia-api/pull/69

**Pull request closed without merging**
