### PR TITLE
fix(rest): Fix Blob issue for IE9 and lower.

### PR DESCRIPTION
**Pull request by RWOverdijk**
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/94)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/spoonx/aurelia-api/94)*

**Comment by jasonhjohnson** [comment]
Are there plans to merge this in?

**Comment by RWOverdijk** [comment]
@jasonhjohnson We're still talking about it. One of the options is not using the json util at all. Still checking the impact (to be fair, it's IE9, which has limited support).

I expect this to be settled by tomorrow.

**Comment by doktordirk** [comment]
ha, as basically usual i first had to fix an aurelia bug, so i only will have time to look into it tomorrow

**Comment by doktordirk** [comment]
bryans 'tough luck' answer is *censored*. i'll try to PR something to the fetch-client later

**Comment by doktordirk** [comment]
https://github.com/aurelia/fetch-client/pull/61

**Comment by RWOverdijk** [comment]
Ack, nice work :)

**Comment by doktordirk** [comment]
@RWOverdijk well actually, since we don't use the Blob, utils json is only JSON.stringifing for us. hence, we just could use that directly, or?

**Comment by RWOverdijk** [comment]
That's what I said on gitter, earlier. We can use JSON.stringify() and set the header, and be done with it.

**Comment by doktordirk** [comment]
let's do that then

<details><summary><i>Previously, RWOverdijk (Wesley Overdijk) wrote…</i></summary>
> That's what I said on gitter, earlier. We can use JSON.stringify() and set the header, and be done with it.
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/spoonx/aurelia-api/94#-:-KI8VfseaHRV8YQsrWse:1046288267)*

**Comment by doktordirk** [comment]
fixed with https://github.com/SpoonX/aurelia-api/pull/102

**Pull request closed without merging**
