### PR TITLE
fix(rest): use JSON.stringify to prevent ie9 issues

### PR DESCRIPTION
**Pull request by doktordirk**
replaces https://github.com/SpoonX/aurelia-api/pull/94

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/97)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Come to think of it... I remember someone using `application/x-www-form-urlencoded`. Would that still work for them?

**Comment by doktordirk** [comment]
hmm well hasn't changed in that respect i'd think. but maybe better add a test for that

<details><summary><i>Previously, RWOverdijk (Wesley Overdijk) wrote…</i></summary>
> Come to think of it... I remember someone using `application/x-www-form-urlencoded`. Would that still work for them?
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/spoonx/aurelia-api/97#-:-KIax_Ma36fuZY3q3Og4:-1436201775)*

**Comment by doktordirk** [comment]
@RWOverdijk yeah, as i said (basically), wasn't working before either. fixed that and Blob, FormData are not stringified now

**Comment by doktordirk** [comment]
hmm needs tests for Blob and FormData and/or separation for the default content-type

**Comment by doktordirk** [comment]
to be replaced

**Pull request closed without merging**
