### PR TITLE
Fix code typos in README and "getting started" doc

### PR DESCRIPTION
**Pull request by AdamWillden**

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk can be merged

**Comment by AdamWillden** [comment]
Noooo I thought I was going to make the commit messages conform to contrib standards lol

**Comment by RWOverdijk** [comment]
Crap. Right. @doktordirk next time I'm not listening to you. :octopus:

**Comment by doktordirk** [comment]
ups

**Comment by RWOverdijk** [comment]
It's not the end of the world. It's a doc file. Besides, I should have paid more attention haha.

**Pull request merged**
