### PR TITLE
refactor: Dependency injection src/config.js

### PR DESCRIPTION
**Pull request by Romanchuk**
Hello, i've seen you had a discussion about IoC https://github.com/SpoonX/aurelia-api/issues/54. And i've added dependency injection into src/config.js.

Sadly that 'aurelia-fetch-client' doen't provide an interface for HttpClient, so i inject it by concrete type.

P.S. Sorry for commit comment message format. I've commited before read your guidelines

### CODE REVIEW

**Comment by doktordirk** [comment]
ah, very interesting.

**Comment by RWOverdijk** [comment]
I don't know what to make of this. Why is it closed?

**Comment by doktordirk** [comment]
Don t know. I.ll keep it in mind though

**Comment by Romanchuk** [comment]
Sorry guys, i wanted to do more experiments with DI in Aurelia. Aurelia docs are not so detailed as could be. I'm going to update my code and reopen it  soon(or create another request).

**Pull request closed without merging**
