### PR TITLE
refactor(project): removed extend dependency

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
:-1: I can't see the problem with extend being used here. It's more readable and logical in the scope.

**Comment by AdamWillden** [comment]
Out of interest. Don't some aurelia repos also requie extend? If so it might not be a bad dependency to have. I agree it's less readable but I'd be easy either way.

**Comment by doktordirk** [comment]
Official Aurelia client repos dont have any external dependencies. I as well prefer to avoid them particularly if is only two lines needed

**Comment by RWOverdijk** [comment]
@doktordirk Orm uses it, too (less predictable) for recursive merging of objects. Seeing how extend itself is ~80 short lines of code, unminified, I really don't think this is worth doing.

**Comment by doktordirk** [comment]
accepted. i'll might come back to it later though

**Pull request closed without merging**
