### PR TITLE
feat(rest): trailing slash option

### PR DESCRIPTION
**Pull request by doktordirk**
readme update still missing

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/145)

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk that seems quite a bit more convoluted. just keeping trailing slashes seems easier. anyways, other than user/1 all requests have kept them previously i think. hence the other option might get simplified. 

as for accepting trailing slashes. isn't it more likely the other way round. all servers will accept that trailing slash most likely

**Comment by RWOverdijk** [comment]
@doktordirk I agree with you. But if we keep the trailing slash it'll be a BC break. We could do that still, I suppose, but it's magic. Magic scares people (and makes for odd issues). I personally think making it configurable is a better idea, but I'd love your input :)

**Comment by doktordirk** [comment]
your right about magic isn't a good design choice. but this is rather about consistent behaviour since you are wrong, it's not (very) breaking. it was only inconsistent before. 
as you can see maybe in the other commit, the only place where the trailing slash wasn't maintained previously is with criteria as id. (path/id) in all other cases, trailing slashes had been maintained (eg is path/?id=1 already). hence, i thing in this case, the better option is too keep it simple and use the other option

**Comment by doktordirk** [comment]
we'll use the other option for now

**Pull request closed without merging**
