### PR TITLE
use spoonx-tools, better typings, add findOne... methods

### PR DESCRIPTION
**Pull request by doktordirk**
closes https://github.com/SpoonX/aurelia-api/issues/149

This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/153)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
I'll have to trust you on this one, I can't review right now.

@VMBindraban can you review this?

**Comment by doktordirk** [comment]
@RWOverdijk ah, i've added flowTypes to it. hence, 'src' might not be able to be used in the browser directly. in 'dist', is a version without flow types though

**Comment by VMBindraban** [comment]
:+1:

**Comment by doktordirk** [comment]
i'll make a final swan client and typings test then and merge

**Comment by doktordirk** [comment]
@RWOverdijk  ah, and i need an okay from you for the flow types in the source

**Comment by RWOverdijk** [comment]
@doktordirk You had that okay already :) I like it a lot, and if it ever stops being useful it is really simple to remove. So officially:

👍

**Pull request merged**
