### PR TITLE
fix(config): pre-populate defaults before invoking user config function

### LINKED ISSUE #222: POST/PUT requests are not properly sending json body
My code worked in 3.1.1 and earlier, but after updating to 3.2.0 latest, all POST and PUT requests in my application are broken.

The request payload is coming across as "[object Object]" instead of the expected json stringified object. Request header is getting this set to "Content-Type: text/plain;charset=UTF-8", expected it to auto-set it to "application/json" as it did before.

Reverted API (and ORM and Authentication dependencies) to 3.1.1, and those same calls are coming back with the json string in body and 'application/json' as expected.

### PR DESCRIPTION
**Pull request by carusology**
Fixes #222 

~I can't seem to run the tests locally, so let's see if CI can do it.~

I got the tests to run, and added one for explicitly setting defaults to null and not setting defaults at all.

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/223)

### CODE REVIEW

**Comment by carusology** [comment]
@RWOverdijk CI config appears to have some cached creds which are now invalid. 😞 

>Unauthorized response for GitHub API.
>Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

**Comment by RWOverdijk** [comment]
Ah yeah... Fixed. I'll click update branch :D

**Review by RWOverdijk — APPROVED** [review]
Very nice PR. 👍

**Comment by RWOverdijk** [comment]
Published as v3.2.1

Nice version number. Guess we have liftoff ✈️

**Pull request merged**
