### PR TITLE
feat(rest): add a flag to enable RFC6570 uri templates

### LINKED ISSUE #174: FEAT: support of traditional URI request templates (RFC6570) when building query strings
**Reason**: Some endpoints require the old syntax for passing array-like query parameters, like the following `?sort=name&sort=surname` (one popular example is Spring Data REST).

Now the `Rest` object lacks the ability to enable this flag, but the underlying `aurelia-path` lib that it uses to build query strings supports a `traditional` flag to enable RFC6570.

I propose a PR that adds a `useTraditionalUriTemplates` property to the `Rest` class, that's disabled by default. One can simply set this to `true` to enable the behavior for the whole instance.
I prefered not to alter all the method signatures, and by the way is more common to have the RFC6570 syntax enabled for the entire API surface and not for some methods only..

### PR DESCRIPTION
**Pull request by nexbit**
Resolves #174 by adding a `useTraditionalUriTemplates` boolean property to the `Rest` class

---

This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/175)

### CODE REVIEW

**Comment by doktordirk** [comment]
can you add a simple test (eg to also pick up a broken aurelia-path)?

**Comment by nexbit** [comment]
@doktordirk I'm writing tests for each of the `Rest` methods, but to be more effective I need to make a small change to `spoonx-tools`.
Specifically, I'm going to add a `originalUrl` property to all the `server` responses. That PR is mandatory for the new tests contained in this PR to work.

**Comment by nexbit** [comment]
I'm going to publish the tests anyway, even if the CI step will fail. It will succeed as soon as the `spoonx-tools` package will be updated with my PR...

**Comment by doktordirk** [comment]
you can try using interface. it still gets transpiled to js fine

**Comment by nexbit** [comment]
@doktordirk Sorry, but I can't really grasp this "somewhat hybrid ES6 with a spray of types" :-/
I'm used to write proper typescript, and avoid JS whenever I can, for the sake of my mental sanity..
So, I know how to write an interface in typescript, but I don't know what kind of interface declaration the transpiler you use can digest. I tried to declare an `RestOptions` interface, but the generated d.ts is now a crap of nonsense..

**Comment by doktordirk** [comment]
it's the same custom d.ts generator aurelia uses. anyways
```js
/**
* Represents a plugin to the module loader.
*/
interface LoaderPlugin {
  /**
  * Fetches the resource.
  * @param address The address of the resource.
  * @return A Promise for the requested resouce.
  */
  fetch(address: string): Promise<any>;
}
```
should work fine. i'm not a ts expert and i though that'll be it

**Comment by nexbit** [comment]
Found the culprit. It doesn't support exported interfaces, that TS does. I declared the interface local (no export) and it works fine.

**Comment by doktordirk** [comment]
ps: i guess the editor would pick up the docblocks for it. so i guess it'll be nice to add them like in the aurelia sample above

**Comment by nexbit** [comment]
Comments done. Anyways, when are you going to publish new spoonx-tools? otherwise CI will continue to fail here..

**Comment by doktordirk** [comment]
tx!

only @RWOverdijk can do that (for good reason). so, at times it takes a while

**Comment by doktordirk** [comment]
@nexbit test works again, but linting failed

**Comment by doktordirk** [comment]
@nexbit test works again, but linting failed

**Pull request merged**
