### PR TITLE
chore(project): add bower.json

### PR DESCRIPTION
**Pull request by doktordirk**
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/113)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Why?

**Comment by doktordirk** [comment]
hehe, don't ask me. aurelia is adding them. anyways, their setup is still constantly changing, and i don't intend to invest much into until they have settled

**Comment by doktordirk** [comment]
current aurelia rc1 conclusion: keep our build, add bower and that typings json to allow typings install of the d.ts from our repo. hence, nothing breaking but ts user still will have the same trouble they.ll have with aurelia rc1 naturally

**Comment by RWOverdijk** [comment]
So, do we or do we not need this?

**Comment by doktordirk** [comment]
need? maybe not, but where is the problem?

**Comment by RWOverdijk** [comment]
No problem, I just don't like clutter. I don't mind either way 👍

**Pull request merged**
