### PR TITLE
feat(Rest): add patch method

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Yay for methods :D 

* Rename commit
* add tests
* update docs

**Comment by doktordirk** [comment]
* wanted to do that in the merge message
* is planned
* is planned
:smile:

**Comment by RWOverdijk** [comment]
That should be done _before_ the merge message as it's still a record in versioning. Otherwise it looks pretty awesome

**Comment by doktordirk** [comment]
@RWOverdijk seems express doesn't like lowercase patch. i uppercased all default methods then

**Comment by RWOverdijk** [comment]
@doktordirk I use express and it doesn't care. Is this new in express 4 perhaps?

**Comment by doktordirk** [comment]
that with 4. but the problem is only with patch vs PATCH. the others work, just though changing the defaults to upper would still be BC. give 'patch' in our tests and see if it works, didn't respond for me

**Comment by RWOverdijk** [comment]
It's not BC if someone relies on it. I guess that's the thing with BC.. Either way I'm fine with using upper case.

**Comment by RWOverdijk** [comment]
👍

**Comment by doktordirk** [comment]
renamed first commit

**Comment by RWOverdijk** [comment]
Still :+1: haha

**Pull request merged**
