### PR TITLE
Stringify request body fix for #154

### LINKED ISSUE #154: Rest.post function submits raw string requests
Hi I found an issue with Rest.post submitting requests with raw strings yet the header is "application/json".

My user case is I need to submit a URL to a REST service. Using Rest's post function creates a request with a raw string body. The REST service's JSON parser rightly thinks the URL is a JSON object due to the colon after http.

### PR DESCRIPTION
**Pull request by alxwest**
This PR is to fix #154 by stringifying everything rather than just objects.

NB. I can't create a valid test as Karma only accepts strict JSON objects and not lone JSON strings.

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/155)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
None of this will work if the type isn't an object. For that reason I don't think this PR solves anything. What was the idea?

**Comment by doktordirk** [comment]
@RWOverdijk see issue above

**Comment by doktordirk** [comment]
not really. the PR JSON.stringify when the body isn.t an Object which makes no sense

**Comment by doktordirk** [comment]
a string is not a valid JSON http://www.json.org/

**Pull request closed without merging**
