### PR TITLE
fix(config): transfer defaults from the endpoint client configuration…

### PR DESCRIPTION
**Pull request by doktordirk**
… function to the endpoint defaults

---
This change is [Reviewable](https://reviewable.io/reviews/spoonx/aurelia-api/215)

### CODE REVIEW

**Comment by soulhunter1987** [comment]
Hi. This change breaks default behavior when there is no configuration (withDefaults) on endpoint client, because client defaults are an empty object, not null. When using this code from manual:
```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()

    // Add this:
    .plugin('aurelia-api', config => {
      config.registerEndpoint('github', 'https://api.github.com/');
    });

  aurelia.start().then(a => a.setRoot());
}
```
I get queries without Content-type: application/json and Accept: application/json being set, because they are discarded on this line:
```javascript
// transfer user defaults from http-client to endpoint
+      if (typeof newClient.defaults === 'object' && newClient.defaults !== null) {
+        this.endpoints[name].defaults = newClient.defaults;
+      }
```

**Comment by soulhunter1987** [comment]
I had to change code like this to get it working:
```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()

    // Add this:
    .plugin('aurelia-api', config => {
      config.registerEndpoint('github', 'https://api.github.com/').withDefaults(null);
    });

  aurelia.start().then(a => a.setRoot());
}
```

**Comment by doktordirk** [comment]
i think the error is here
```
    // set custom defaults to Rest
    if (defaults !== undefined) {
      this.endpoints[name].defaults = defaults;
    }
```
resp here
```
registerEndpoint(name: string, configureMethod?: string|Function, defaults?: {}, restOptions?: RestOptions): Config {
 ```
when , `defaults` defaults to {} and not stay undefined

**Comment by soulhunter1987** [comment]
No, your defaults come from third argument to "registerEndpoint", which is really undefined in this case. I did several tests and pointed it out exactly. But FetchClient defaults are really an empty object by default, but you check againts null

**Comment by doktordirk** [comment]
there are too many defaults floating around :(

anyways, works for me seemingly.  the request options are set in rest.js
```js
export class Rest {
  defaults: {} = {
    headers: {
      'Accept'      : 'application/json',
      'Content-Type': 'application/json'
    }
  };
  request(method: string, path: string, body?: {}, options?: {}, responseOutput?: { response: Response}): Promise<any|Error> {
    let requestOptions = extend(true, {headers: {}}, this.defaults, options || {}, {method, body});
 ```
so, as long as this(endpoint).defaults aren't changed in config or they are overwriting by options, the headers are those default json types.

the endpoint defaults can be changed in registerEndpoint
here (as i said, i wonder why they are not {} by default here)
 ```
   if (defaults !== undefined) {
      this.endpoints[name].defaults = defaults;
    }
```
and here  (neither  newClient.defaults being null nor undefined should enter there)
```
   if (typeof newClient.defaults === 'object' && newClient.defaults !== null) {
        this.endpoints[name].defaults = newClient.defaults;
      }
```

so, i am a bit lost atm

**Comment by doktordirk** [comment]
am also confused there
```js
    // Add this:
    .plugin('aurelia-api', config => {
      config.registerEndpoint('github', 'https://api.github.com/').withDefaults(null);
    });
```
registerEndpoint() returns config (and not the fetch-client) and has no withDefaults()!?

**Comment by soulhunter1987** [comment]
Hoops, this is my mistake. My working code:
```javascript
// Add this:
    .plugin('aurelia-api', config => {
      config.registerEndpoint('github', client => {
        client.withBaseUrl('https://api.github.com/').withDefaults(null);
      });
    });
```

**Comment by doktordirk** [comment]
i that case it's more an error in the docs rather than in the implementation. the 'normal' configuration would be 
```
config.registerEndpoint('github', 'https://api.github.com/')
```
when using a configuration function for the fetch client like
```
config.registerEndpoint('github', client => {
        client.withBaseUrl('https://api.github.com/');
      });`
```
it is assumed that you want to use your own defaults and not the provided ones for the 'normal' configuration. you configure the fetch client yourself instead of letting aurelia-api do that, so you probably want it the way you configured it, that is, without defaults. i'm not saying that the current implementation there must be the best, but i'm not sure if it's a good idea to change it as it might break code for users who want and easy way to configure the fetch client themself

**Pull request merged**
